# Generated by Django 3.0.5 on 2020-04-21 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translator_name', models.CharField(max_length=200, verbose_name='Название статьи')),
            ],
        ),
        migrations.CreateModel(
            name='TrainText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Translator')),
            ],
        ),
    ]
