# Generated by Django 3.0.5 on 2020-04-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translator',
            name='translator_name',
            field=models.CharField(max_length=200, verbose_name='Имя переводчика'),
        ),
    ]
