# Generated by Django 3.0.5 on 2020-04-24 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200421_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва параметра')),
            ],
        ),
        migrations.CreateModel(
            name='TrainDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='Елемент')),
                ('value', models.FloatField(verbose_name='Частота')),
                ('analysisParam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.AnalysisParam')),
                ('translator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Translator')),
            ],
        ),
        migrations.CreateModel(
            name='TestDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='Елемент')),
                ('value', models.FloatField(verbose_name='Частота')),
                ('analysisParam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.AnalysisParam')),
                ('testText', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TestText')),
            ],
        ),
    ]
