# Generated by Django 3.0.5 on 2020-04-24 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_analysisparam_testdictionary_traindictionary'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalNumEl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysisParam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.AnalysisParam')),
                ('translator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Translator')),
            ],
        ),
    ]
