# Generated by Django 3.0.5 on 2020-04-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_totalnumel'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalnumel',
            name='value',
            field=models.FloatField(default=0, verbose_name='Загальна величина'),
        ),
    ]
