# Generated by Django 3.0.5 on 2020-04-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_totalnumel_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisparam',
            name='code',
            field=models.IntegerField(default=0, verbose_name='Код'),
        ),
    ]
