# Generated by Django 3.0.5 on 2020-04-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_analysisparam_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testdictionary',
            name='key',
        ),
        migrations.RemoveField(
            model_name='testdictionary',
            name='value',
        ),
        migrations.RemoveField(
            model_name='traindictionary',
            name='key',
        ),
        migrations.RemoveField(
            model_name='traindictionary',
            name='value',
        ),
        migrations.AddField(
            model_name='testdictionary',
            name='file',
            field=models.FileField(default='some file', upload_to=''),
        ),
        migrations.AddField(
            model_name='traindictionary',
            name='file',
            field=models.FileField(default='some file', upload_to=''),
        ),
    ]
