# Generated by Django 3.0.5 on 2020-04-24 18:04

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200424_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traindictionary',
            name='file',
            field=models.FileField(default='some file', storage=django.core.files.storage.FileSystemStorage(location='/media/trained'), upload_to=''),
        ),
    ]
