# Generated by Django 3.0.5 on 2020-04-25 11:30

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200424_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traindictionary',
            name='file',
            field=models.FileField(default='some file', storage=main.models.OverwriteStorage(), upload_to=''),
        ),
    ]
